### PR TITLE
Chore: upgrades rxjs resolution to 7.3.0

### PR DESCRIPTION
**Pull request by hugohaggmark**
Opened this PR because of this [comment](https://github.com/grafana/grafana/pull/37913#pullrequestreview-731459093).

### CODE REVIEW

**Review by jackw — APPROVED** [review]
Great stuff @hugohaggmark ! 👏

**Comment by hugohaggmark** [comment]
@jackw seems like the build step `plugin_workflow` is stuck?

**Comment by hugohaggmark** [comment]
Not sure why this is stuck, might be because we stopped using the GitHub actions from https://github.com/grafana/plugin-workflows. I'm going ahead and merging this anyway because the Drone build is green.

**Comment by yesoreyeram** [comment]
@hugohaggmark - Can all the existing plugins use this resolution? will that cause any conflicting issues when using older versions of grafana with latest rxjs resolution?  Some plugin depends on `@grafana/{ui/data/runtime/toolkit}` packages with version 7.x

**Comment by hugohaggmark** [comment]
> @hugohaggmark - Can all the existing plugins use this resolution? will that cause any conflicting issues when using older versions of grafana with latest rxjs resolution? Some plugin depends on `@grafana/{ui/data/runtime/toolkit}` packages with version 7.x

I think that is another issue that needs to be addressed in the future. I think right now we always target the latest version of Grafana. Please correct me if I'm wrong @jackw @mckn

**Comment by mckn** [comment]
> > @hugohaggmark - Can all the existing plugins use this resolution? will that cause any conflicting issues when using older versions of grafana with latest rxjs resolution? Some plugin depends on `@grafana/{ui/data/runtime/toolkit}` packages with version 7.x
> 
> I think that is another issue that needs to be addressed in the future. I think right now we always target the latest version of Grafana. Please correct me if I'm wrong @jackw @mckn

That is correct but we are planning on improving the toolkit in `v8.3` to make it use template depending on its current version. It will resolve issues like this.

**Comment by yesoreyeram** [comment]
FYI. All the Grafana enterprise plugins are using `@grafana/{ui/data/runtime/toolkit}:7.5.0` and performing rxjs resolution to `6.6.3`.  They will stick with it atleast until next few months.  Wondering what impact they will have when customer uses latest grafana having this PR. Are they backward compatible?

**Pull request merged**
